# Generated by Django 2.2.1 on 2019-05-13 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20190510_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curssos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codi_curs', models.CharField(max_length=8, verbose_name='codi')),
                ('nom', models.CharField(max_length=20, verbose_name='curs')),
                ('estat', models.IntegerField(verbose_name='estat')),
                ('data_inici', models.DateField(auto_now_add=True, verbose_name="Data d'inici")),
                ('data_fi', models.DateField(auto_now=True, verbose_name='Data final')),
                ('hores', models.IntegerField(verbose_name='hores')),
            ],
            options={
                'verbose_name': 'curssos',
                'verbose_name_plural': 'curssos',
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='projects', verbose_name='Imagen'),
        ),
        migrations.CreateModel(
            name='Inscripcions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.IntegerField(verbose_name='ordre')),
                ('nom', models.CharField(max_length=20, verbose_name='nom')),
                ('cognoms', models.CharField(max_length=40, verbose_name='cognoms')),
                ('dni', models.CharField(max_length=9, verbose_name='dni')),
                ('telefon', models.IntegerField(verbose_name='telefon')),
                ('correu', models.CharField(max_length=20, verbose_name='correu')),
                ('sexe', models.CharField(max_length=10, verbose_name='sexe')),
                ('edat', models.IntegerField(verbose_name='eadt')),
                ('codi_curs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Curssos')),
            ],
            options={
                'verbose_name': 'incripciones',
                'verbose_name_plural': 'incripciones',
            },
        ),
    ]
